// Bộ component dùng chung KBIT — nhúng từ @kbit/ui (đồng nhất nhận diện).
// Import: import { Button, Card, Table } from '@/components/kbit'
export { Badge, badgeVariants, type BadgeProps } from './badge'
export { Button, buttonVariants, type ButtonProps } from './button'
export { Card, CardHeader, CardContent, CardFooter, type CardProps } from './card'
export { ConfirmDialog, type ConfirmDialogProps } from './confirm-dialog'
export { EmptyState as KbitEmptyState, type EmptyStateProps } from './empty-state'
export { Input, type InputProps } from './input'
export { Modal, type ModalProps } from './modal'
export { PageHeader as KbitPageHeader, type PageHeaderProps } from './page-header'
export { Pagination, type PaginationProps } from './pagination'
export { Select, type SelectProps, type SelectOption } from './select'
export { Skeleton, SkeletonTable, SkeletonCard, type SkeletonProps } from './skeleton'
export { Spinner } from './spinner'
export { Table, Thead, Tbody, Tr, Th, Td } from './table'
export { Textarea, type TextareaProps } from './textarea'
